### ISSUE TITLE
Breaking Chorus Flowers on other people's claims

### ISSUE THREAD

**Issue by Zaino60** [GriefPrevention/GriefPrevention#1319]
### What happened:
You can use any projectile to grief other player's chorus flowers in claimed land even if you don't have permission to build in such claims. The "no permission" message pops up but the block still actually breaks and not only visually.

### What was expected:
Being unable to grief chorus flowers on claimed lands.

### Steps to reproduce:
1. Throw a projectile to a chorus flower on a claimed land you don't have permission to build at
2. ???
3. Profit!

### Server and GriefPrevention version:
Paste of `/version`: This server is running Paper version git-Paper-449 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.17.1-2b69191

### Stack trace/error or server log
No errors

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 200
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 180
      UnusedClaimDays: 180
      AllClaims:
        DaysInactive: 180
        ExceptWhenOwnerHasTotalClaimBlocks: 20000
        ExceptWhenOwnerHasBonusClaimBlocks: 20000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/warp;/spawn;/tpa;/tpaccept
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: false
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 10
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: gkick %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: false
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 1
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: false
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


```

### Debugging steps attempted

- [X] I attempted running only GriefPrevention on the server
  - [X] Issue still occurs even if GriefPrevention is the only plugin running
- [X] I attempted testing for the issue on a new server
  - [X] Issue still occurs even after testing on a new server
- [X] I attempted testing for the issue with the vanilla client (no mods)
  - [X] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment]
Pretty sure this was fixed some time ago. The fix is janky (I have to manually re-add the block) because ProjectileHitEvent isn't cancelable, and no other event is called when this happens. Are you sure it's actually gone? (try reconnecting).

**Comment by Zaino60** [comment]
yes 100% the bug still happens, and every single time, at least on Paper 1.16.5

**Comment by RoboMWM** [comment]
guess we need to find a new solution then.

**Comment by lordrius** [comment]
> Pretty sure this was fixed some time ago. The fix is janky (I have to manually re-add the block) because ProjectileHitEvent isn't cancelable, and no other event is called when this happens. Are you sure it's actually gone? (try reconnecting).

If it helps, Paper's ProjectileHitEvent implements Cancellable.
https://papermc.io/javadocs/paper/1.16/org/bukkit/event/entity/ProjectileHitEvent.html

**Comment by RoboMWM** [comment]
Yea I've been aware of that API, however GP is aimed to be compatible with CB.

**Comment by Jikoo** [comment]
Closed by #1424
