### ISSUE TITLE
IllegalArguments being thrown often

### ISSUE THREAD

**Issue by doughmination** [GriefPrevention/GriefPrevention#2444]
### Observed Behavior

Error matching to IllegalArguments being thrown often (I have a detection for this and can cause my server to come offline due to a custom error logging script)

### Expected Behavior

IllegalArguments should not be being thrown

### Reproduction steps

Run any paper 1.21.4 server with v16.18.3 and place the mentioned stack trace items

### Stack trace or error log

```shell
world-1  | [19:58:02 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: REDSTONE_WALL_TORCH isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:267) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:533) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1383) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | [19:58:10 INFO]: TheTidark390 issued server command: /back
world-1  | [19:58:34 INFO]: TheTidark390 issued server command: /home home
world-1  | [19:59:14 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: WALL_TORCH isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:267) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:533) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1383) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | [20:00:35 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: REDSTONE_WALL_TORCH isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:267) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:533) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1383) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | [20:02:15 INFO]: Death > SwissCat was slain by Piglin Brute!
world-1  | [20:02:20 INFO]: [Not Secure] SwissCat > ouch
world-1  | [20:04:05 ERROR]: Could not pass event PlayerItemConsumeEvent to WorldGuardExtraFlags v4.2.3
world-1  | java.lang.NoClassDefFoundError: org/bukkit/potion/Potion
world-1  |      at WorldGuardExtraFlags.jar/net.goldtreeservers.worldguardextraflags.listeners.PlayerListener.onPlayerItemConsumeEvent(PlayerListener.java:130) ~[WorldGuardExtraFlags.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:3991) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:2026) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3881) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2749) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3866) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3117) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.entity.player.Player.tick(Player.java:298) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:865) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:340) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.Connection.tick(Connection.java:607) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:256) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.tickConnection(MinecraftServer.java:1762) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.dedicated.DedicatedServer.tickConnection(DedicatedServer.java:427) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1738) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.Potion
world-1  |      ... 24 more
world-1  | [20:04:16 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: WALL_TORCH isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:267) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:533) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1379) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | [20:04:16 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: WALL_TORCH isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:267) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:533) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1379) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | [20:04:17 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: WALL_TORCH isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:267) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:533) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1379) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

world-1  | [20:13:54 ERROR]: Could not pass event PlayerSignOpenEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: SPRUCE_WALL_SIGN isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.PlayerSignOpenHandler.onPlayerSignOpen(PlayerSignOpenHandler.java:31) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerSignOpenEvent(CraftEventFactory.java:295) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerSignOpenEvent(CraftEventFactory.java:287) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.level.block.SignBlock.openTextEdit(SignBlock.java:201) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.level.block.SignBlock.useWithoutItem(SignBlock.java:137) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.useWithoutItem(BlockBehaviour.java:907) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:517) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1383) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | [20:13:55 ERROR]: Could not pass event SignChangeEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: SPRUCE_WALL_SIGN isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onSignChanged(BlockEventHandler.java:140) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at net.minecraft.world.level.block.entity.SignBlockEntity.setMessages(SignBlockEntity.java:189) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.level.block.entity.SignBlockEntity.lambda$updateSignText$4(SignBlockEntity.java:151) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.level.block.entity.SignBlockEntity.updateText(SignBlockEntity.java:163) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.level.block.entity.SignBlockEntity.updateSignText(SignBlockEntity.java:151) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3464) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$16(ServerGamePacketListenerImpl.java:3451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
world-1  |      at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1561) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
world-1  | [20:20:02 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.18.3
world-1  | java.lang.IllegalArgumentException: CAVE_VINES isn't an item
world-1  |      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-33.3.1-jre.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.of(ItemStack.java:60) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:156) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:135) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:122) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:105) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.GriefPrevention.allowBuild(GriefPrevention.java:3499) ~[GriefPrevention.jar:?]
world-1  |      at GriefPrevention.jar/me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:267) ~[GriefPrevention.jar:?]
world-1  |      at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
world-1  |      at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:458) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:451) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:533) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:45) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1561) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-203-34c794d]
world-1  |      at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Server version

```shell
This server is running Paper version 1.21.4-207-main@1a7288a (2025-03-09T18:15:59Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-203-34c794d (MC: 1.21.4)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.3
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world_the_end: Disabled
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - SHORT_GRASS
    - DIRT
    - BIRCH_PLANKS
    - SPRUCE_PLANKS
    - COBBLESTONE
    - OAK_PLANKS
    - GLASS
    - RED_WOOL
    - LIGHT_BLUE_WOOL
    - BLUE_WOOL
    - GRASS_BLOCK
    - GRAVEL
    - MAGENTA_WOOL
    - PURPLE_WOOL
    - DEAD_BUSH
    - CYAN_WOOL
    - SNOW
    - SAND
    - BLACK_WOOL
    - FERN
    - LIGHT_GRAY_WOOL
    - JUNGLE_PLANKS
    - YELLOW_WOOL
    - LIME_WOOL
    - BROWN_WOOL
    - ORANGE_WOOL
    - GRAY_WOOL
    - GREEN_WOOL
    - GLASS_PANE
    - PINK_WOOL
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ACACIA_PLANKS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
Server Plugins (32):
Paper Plugins (1):
 
FancyNpcs
Bukkit Plugins (31):
 
BlueMap, Chunky, CyberDeathMessages, DecentHolograms, Essentials, EssentialsChat, EssentialsDiscord, EssentialsDiscordLink, EssentialsSpawn, floodgate
FreedomChat, Geyser-Spigot, GriefPrevention, Lootin, LuckPerms, PlaceholderAPI, PlugManX, ProtocolLib, RapidLeafDecay, ServerListPlus
SuperVanish, TAB, *TGCustom, TrueSpiderEyes, Vault, ViaBackwards, ViaVersion, voicechat, WorldEdit, WorldGuard
WorldGuardExtraFlags
```

### Running without GriefPrevention

- [x] I attempted running the server without GriefPrevention installed.
- [x] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [x] I attempted running only GriefPrevention on the server.
- [x] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [x] I attempted testing for the issue on a new server.
- [x] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [x] I searched for similar issues before submitting this bug report.

**Comment by doughmination** [comment]
Also I am using docker to run the server using itsz/minecraft-server, and using Aikar's JVM Flags (altho this shouldn't affect it)

**Comment by QarthO** [comment]
Makes a lot of sense. If ur gonna run an old version on a new server it's gonna break. Why not first check if there's an update? I'd recommend always checking for updates if you come across any issues (this is for any software, not just Minecraft stuff)

**Comment by Jikoo** [comment]
As QuarthO said, the problem is that you're using an outdated version of GP. This issue was resolved in 16.18.4.

**Comment by doughmination** [comment]
> Makes a lot of sense. If ur gonna run an old version on a new server it's gonna break. Why not first check if there's an update? I'd recommend always checking for updates if you come across any issues (this is for any software, not just Minecraft stuff)

I wasn't aware at the time of submitting of the update that came out recently. The plugin was updated to 16.18.4 and still throwing the issue

**Comment by Jikoo** [comment]
If you're still encountering issues, please post an updated stack trace. 16.18.4 isn't really recent, it's been out almost a year.
