### ISSUE TITLE
New 1.16 doors and trapdoors don't require /accesstrust to open

### ISSUE THREAD

**Issue by destro174** [GriefPrevention/GriefPrevention#886]
### What happened:
The new door and trapdoor types can be opened by players that don't have /accesstruston the claim.

### What was expected:
These doors and trapdoor types should need /accesstrust to be interacted with

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Paper version git-Paper-89 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.14.0

**Comment by RoboMWM** [comment]
Unless you know the Bukkit Tag (or other similar properties, I know Jikoo mentioned some BlockData classes that could be checked) that could be used to cover all of these materials, a list of the Bukkit Materials would be helpful.

**Comment by destro174** [comment]
this should get all the doors? should also work for trapdoors
```
if (event.getClickedBlock().getState() instanceof Door) {
//do stuff
}
```

**Comment by niqofdez** [comment]
> Unless you know the Bukkit Tag (or other similar properties, I know Jikoo mentioned some BlockData classes that could be checked) that could be used to cover all of these materials, a list of the Bukkit Materials would be helpful.

This? https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by Jikoo** [comment]
Oh, this should have been closed when the PR was merged. I must have messed up the syntax for the autoclose message, or maybe it doesn't support multiple issues.

**Comment by RoboMWM** [comment]
I know you can link issues in the sidebar, but otherwise they have to be included in the commit message and I may have inadvertently taken that out.

**Comment by JoshA20** [comment]
Can confirm, griefprevention doesn't block users from using nether trapdoors in claims regardless of what is adjusted in configuration files.

**Comment by RoboMWM** [comment]
@JoshA20 the fix for this is in the upcoming release 16.14.1 https://github.com/TechFortress/GriefPrevention/milestone/13

**Comment by Hazugg** [comment]
and how can you do with that problem? will they get an update for that? or is there some way to solve it?
help pls, my players report about it, thanks.

**Comment by Jikoo** [comment]
Download a dev build off the CI. https://ci.appveyor.com/project/RoboMWM39862/griefprevention/

Current master build is [here](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/34402052/artifacts).

**Comment by Hazugg** [comment]
Thank you very much, this compilation works.

**Comment by JHarris12345** [comment]
When will this put fixed in a public release though?

**Comment by RoboMWM** [comment]
I would like to pull the unexpected spike of PRs before releasing, but given the scope of some PRs, if I can't find time to pull them all in this week I'll start cutting a release.

**Comment by joex92** [comment]
is this matter solved? because a friend of mine told me it's still not protecting nether wood blocks...

**Comment by bigpresh** [comment]
> is this matter solved? because a friend of mine told me it's still not protecting nether wood blocks...

Reading this issue's history it appears it was fixed back in 2020 when the issue was closed and references the PRs which fixed it.

If you can reproduce the issue with the latest GriefPrevention build, please raise a new ticket filling out all info requested by the issue template - versions in particular.
